version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/models:/app/models
    environment:
      - VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY}

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
